# Project-wide Gradle settings — MaduraApp
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# Backend URL — sobreescribir en local.properties si difiere
maduraapp.api.baseUrl=http://3.215.43.61:8000/
